export default {
  name: 'Empresa B',
  endDate: '12/31/2018',
  auditor: 'PwC',

  recomendation: [
    {
      unit: 'Empresa B1',
      cd: '',
      description: '',
      periodEnd: '',
      finalConclusion: '',
      fsli: '',
      internalControl: '',
      businessProcess: '',

      assertions: '',
      response: '',
      deficiency: '',
      misstatement: '',
      exposedAccountsInterim: '',
      exposedAccountsAnnual: '',
      misstatementFinancial: '',
      factors: '',
      significantDeficiency: '',
      rationale: '',
      compensatingControls: '',
      descriptionControls: '',
      testingDocumented: '',
      materialWeakness: '',
      documentRationale: '',
      controlDeficiencies: '',
      aggregationDescription: '',
      sourceRef: '',
      title: '',
      SubProcess: '',
      fsliOrDisclosure: '',
      roll: '',
      controlNo: '', // number
      controlTitle: '',
      auditResponse: '',
      aggregationReference: '',
      IsReportedToManagement: '',
      ExceptionAmount: '',
      AffectedPopulationAmount: '',
      RootCause: '',
      Implication: '',
      Recommendation: '',
      ResponsiblePerson: '',
      TargetDate: '',
    },
  ],
};
